### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by alengwenus** [alengwenus/pypck#12]
More tests have to be implemented to increase the test coverage.

**Comment by maximilianriemensberger** [comment]
@alengwenus 

While working on the group discovery issue #27, I ran into a minor few `PckParser` related bugs mostly `.` instead of `\.`. Before finishing the groups stuff, I'm considering adding a set of tests for the `PckParser`, the `PckGenerator`, and `Input` and friends. I'd first focus on unittests of these classes without involvement of asyncio to speed up the test execution and keep this first level of parser and generator testing small and self-contained. 

Right now the tests for example for SKH are in a test file for SKH and test for parser up to the connection manger. I'd instead propose a set of test files that test the Parser, Generator, and Input classes for each message and command. The alternative would be to stick to the current form and have a test file for each message and each command that test for low level parser or generator up to the high level convenience methods. How would you want to approach it?

**Comment by alengwenus** [comment]
@maximilianriemensberger 
I don't have any preferences here. I'm fine with your suggestion. Unittests are fine as I don't think that the interfaces for PckParser, PckGenerator and Input will change in the near future.
(Btw.: The classes with their static methods are relics from the Java conversion. Back then, I just wanted to get over with them quickly. Personally I don't like them that much because they're not very "_pythonic_" :smirk:)

If we feel that the test files are getting to big and difficult to maintain, we can still choose another format.
