### ISSUE TITLE
Segment coupler scan questions

### ISSUE THREAD

**Issue by maximilianriemensberger** [alengwenus/pypck#56]
`PchkConnectionManager.async_connect` forces a segment coupler scan.  This can be overridden by setting `SK_NUM_TRIES=0` which appears to be interpreted as an indicator that there are no segment couplers (scan completed is set). There is no way to delay the scan until later time. 

Additionally, `PchkConnectionManager.is_ready` checks whether the segment coupler scan is completed with a comment that nothing should be sent before `is_ready` indicates true.

This leads me to a couple of questions:

1. Deployment with a single segment (without any segment couplers)
   * The scan is not necessary and `SK_NUM_TRIES` should be set to zero?
   * Local and physical seg id will always be zero?
   * Modules and groups on the local segment can only be addressed with segment id zero?
2. Deployment with more than one segment
   * Do modules actually know about their segment id?
   * Does a module 5 on segment 5 respond to a command directly respond to `>M005005!LEER` if PCHK is on the same segment, or does that command go to the segment coupler which reflects it to the module, or doesn't any of that work at all?
   * Presumably, `>M000005!LEER` always works the same on the local segment.
   * Are any of these communication details the reason why certain functions are gated by `segment_scan_completed`?
   * pypck does rewrite the seg_id of commands via `get_physical_seg_id`. Is there a articular reason for it or would sending with the logical seg_id be equivalent?

In my opinion, it would be somewhat clearer and easier to deal with the `is_lcn_connected` states if the there would be a clear distinction between a `async_connect` method that does only connect to the PCHK, does auth, setup operation mode, pings, etc. but does not interact with the bus in any way. And then a method that starts all the necessary/desired bus discovery/scanning process.  Maybe multiple methods like now and a convenience method to do the typical scanning procedures (segment, modules, etc.). Most of it is already handled this way. But the segment coupler scanning appears to be very special.

**Comment by alengwenus** [comment]
Sorry for the delay in answering, but currently I'm quite busy (among other things with a web configuration UI for the HomeAssistant LCN integration).

> `PchkConnectionManager.async_connect` forces a segment coupler scan. This can be overridden by setting `SK_NUM_TRIES=0` which appears to be interpreted as an indicator that there are no segment couplers (scan completed is set). There is no way to delay the scan until later time.
> 
> Additionally, `PchkConnectionManager.is_ready` checks whether the segment coupler scan is completed with a comment that nothing should be sent before `is_ready` indicates true.

The last versions introduced some changes in the connection procedure. Maybe there are some relics from older versions which are not necessary anymore and might need a review.

Unfortunately, I don't have a segment coupler to test. That said, I try to answer your questions as good as I can.

> This leads me to a couple of questions:
> 
> 1. Deployment with a single segment (without any segment couplers)
>    
>    * The scan is not necessary and `SK_NUM_TRIES` should be set to zero?

Correct. 👍 

>    * Local and physical seg id will always be zero?

Correct. 👍 

>    * Modules and groups on the local segment can only be addressed with segment id zero?

Correct. 👍  (but see below)

> 2. Deployment with more than one segment
>    
>    * Do modules actually know about their segment id?

Here it gets a bit more complicated and we have to distinguish between PCK commands and bus telegrams.
As far as I remember, modules do not know anything about their segment id nor do they filter for segment id 0.
On bus telegram level there is an info byte with a cross-segment flag. If the flag is set, the segmen id is considered as a target segment id (where it should go). If it is cleared, the segment id is considered as the source segment id (where it comes from).

If a module sends a command, the bit is set and no other module in the segment will accept this telegram. A segment coupler on the same segment forwards the telegram to the target segment and removes the flag (and also replaces the target segment id with the segment id from the segment the command originated).
Because the cross-segment flag is removed, modules in the target segment will respond to the command and just filter by their module id.

Only if a telegram is sent to segment 0, the cross-segment flag is not set and all modules in the same segment will accept and analyse the telegram.

Now for the PCK commands:
PCK commands sent by the host (LCN-PRO, PCHK) set  the cross-segment flag in the telegram if the target segment id does not equal 0 (so no module in the local segment will react).
PCK Status messages received by the host correspond to telegrams which do not have the cross-segment flag set (because they are from the local segment or the segment coupler removed the flag).

>    * Does a module 5 on segment 5 respond to a command directly respond to `>M005005!LEER` if PCHK is on the same segment, or does that command go to the segment coupler which reflects it to the module, or doesn't any of that work at all?

No it does not, because the cross-segment flag in the telegram will be set (segment id is not 0 -> cross-segment flag is set -> module rejects telegram). So the telegram should be reflected by the segment coupler which removes the cross-segment flag.


>    * Presumably, `>M000005!LEER` always works the same on the local segment.

Yes, but the module will react directly to the corresponding telegram (segment id is 0 -> cross-segment flag is cleared -> module accepts telegram).

>    * Are any of these communication details the reason why certain functions are gated by `segment_scan_completed`?

Yes and no. As I said the connection procedure changed in the last versions. The segment_scan_completed was a future with the result set at the very end of the procedure. Well, waiting for the segment scan to be completed takes time and I'm not sure if it's necessary in every case. Needs some review...

>    * pypck does rewrite the seg_id of commands via `get_physical_seg_id`. Is there a articular reason for it or would sending with the logical seg_id be equivalent?

For clarity:
- `local_seg_id` is the segment id reported by the segment coupler after a scan (if there is one at all)
- physical segment id is given by a command
- logical segment id is used to find a ModuleConnection object in the `PchkConnectionManager.address_conns` dictionary.

ModuleConnection objects (and also the groups) are stored in the `address_conns` dictionary using the `local_seg_id`. If there are segment couplers present, we don't want to have the segment id 0 used because commands sent by a ModuleConnection object need to be tagged with the local (real) segment id. Otherwise (see above), PCHK would not set the cross-segment flag and the command will never leave the local segment.

> In my opinion, it would be somewhat clearer and easier to deal with the `is_lcn_connected` states if the there would be a clear distinction between a `async_connect` method that does only connect to the PCHK, does auth, setup operation mode, pings, etc. but does not interact with the bus in any way. And then a method that starts all the necessary/desired bus discovery/scanning process. Maybe multiple methods like now and a convenience method to do the typical scanning procedures (segment, modules, etc.). Most of it is already handled this way. But the segment coupler scanning appears to be very special.

I completely agree and I already did some work in that direction in the past. However there is room for improvements.
To my excuse: The original openHab implementation was a real mess and it took me a long time to figure out what was supposed to happen. Step by step I tried to clean it up. :smirk:

**Comment by maximilianriemensberger** [comment]
> Sorry for the delay in answering, but currently I'm quite busy (among other things with a web configuration UI for the HomeAssistant LCN integration).

No worries.  And nice idea. I haven't setup HomeAssistant yet for my deployment but it's on the roadmap.

Thanks for the detailed reply it certainly clears up some of my confusion on why the segment stuff is treated the way it is.  I also don't have a segment coupler so I can't help very much in testing the segment things.

> I completely agree and I already did some work in that direction in the past. However there is room for improvements.
> To my excuse: The original openHab implementation was a real mess and it took me a long time to figure out what was supposed to happen. Step by step I tried to clean it up.

No need for an excuse. I looked for quite some time at openhab and it's LCN part. I was pretty relieved that I found pypck. It's just so much nicer and easier to work with especially for playing with the bus an learning how it all works.

I can take a stab at separating connect and bus discovery.
